[package]
name = "day13"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc-traits = { workspace = true }
eyre = "0.6.12"
itertools = "0.13.0"
nom = "7.1.3"
rustc-hash = "2.1.0"
